-- Heartbeat table used by .github/workflows/keep-alive.yml to prevent
-- free-tier pause from inactivity. CheckTimeUtc replaces the original
-- name column; random UUID is retained.

create table if not exists public."keep-alive" (
  id bigint generated by default as identity,
  "CheckTimeUtc" timestamp with time zone not null default now(),
  random uuid not null default gen_random_uuid(),
  constraint "keep-alive_pkey" primary key (id)
);

comment on table public."keep-alive" is
  'Heartbeat rows written by GitHub Actions so the project is not paused for inactivity.';

comment on column public."keep-alive"."CheckTimeUtc" is
  'UTC timestamp of the keep-alive check.';

comment on column public."keep-alive".random is
  'Random UUID written with each keep-alive check.';

alter table public."keep-alive" enable row level security;

create policy "Anonymous can insert keep-alive rows"
  on public."keep-alive"
  for insert
  to anon
  with check (true);

create policy "Anonymous can select keep-alive rows"
  on public."keep-alive"
  for select
  to anon
  using (true);

create policy "Anonymous can delete keep-alive rows"
  on public."keep-alive"
  for delete
  to anon
  using (true);

insert into public."keep-alive" ("CheckTimeUtc", random)
values
  (now(), gen_random_uuid()),
  (now(), gen_random_uuid());

